interface ScrollPosition {
  scrollTop: number;
  scrollHeight: number;
  clientHeight: number;
}

type ScrollDirection = -1 | 0 | 1;

/** Separates user movement from scroll events generated by rendering. */
export class ScrollFollow {
  private lastTop = 0;
  private direction: ScrollDirection | undefined;
  private dragMovedDown = false;
  dragging = false;

  constructor(private readonly state: { autoScroll: boolean }) {}

  private atBottom(position: ScrollPosition): boolean {
    return position.scrollHeight - position.clientHeight - position.scrollTop <= 1;
  }

  pause(): void {
    this.state.autoScroll = false;
    this.direction = undefined;
    this.dragging = false;
    this.dragMovedDown = false;
  }

  reset(follow: boolean, position: ScrollPosition): void {
    this.state.autoScroll = follow;
    this.direction = undefined;
    this.dragging = false;
    this.dragMovedDown = false;
    this.recordLayout(position);
  }

  userIntent(direction: ScrollDirection, position: ScrollPosition): void {
    // Pause before the browser applies the gesture, not in a later frame.
    this.state.autoScroll = direction === 1 && !this.dragging && this.atBottom(position);
    this.direction = direction;
    this.lastTop = position.scrollTop;
  }

  beginDrag(position: ScrollPosition): void {
    this.dragging = true;
    this.dragMovedDown = false;
    this.userIntent(0, position);
  }

  endDrag(position: ScrollPosition): void {
    if (!this.dragging) return;
    this.onScroll(position);
    this.dragging = false;
    this.state.autoScroll = this.dragMovedDown && this.atBottom(position);
    this.endGesture();
  }

  endGesture(): void {
    if (!this.dragging) this.direction = undefined;
  }

  onScroll(position: ScrollPosition): void {
    const delta = position.scrollTop - this.lastTop;
    this.lastTop = position.scrollTop;
    // Delayed scroll events from our last layout/write are not user movement.
    if (Math.abs(delta) < 0.5) return;
    if (delta < 0) this.state.autoScroll = false;
    if (this.direction === undefined) return;
    this.dragMovedDown = delta > 0;
    if (!this.dragging && this.direction >= 0 && delta > 0 && this.atBottom(position)) {
      this.state.autoScroll = true;
    }
  }

  recordLayout(position: ScrollPosition): void {
    this.lastTop = position.scrollTop;
  }
}
